server:
  port: 8081
eureka:
  client:
    enabled: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9099/eureka
    register-with-eureka: true
  instance:
    prefer-ip-address: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: 1007321243
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
