server:
  port: 8081
eureka:
  client:
    enabled: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9099/eureka
    register-with-eureka: true
  instance:
    prefer-ip-address: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: 1007321243
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: USER-SERVICE
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
jwt:
  secret: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.nZU_gPcMXkWpkCUpJceSxS7lSickF0tTImHhAR949Z-Nt69LgW8G6lid-mqd9B579tYM8C4FN2jdhR2VRMsjtA
  expiration: 3600000

